### ISSUE TITLE
Ordering of the tutorial links is flipped

### ISSUE THREAD

**Issue by jamilboashash** [NeCTAR-RC/tutorials#100]
The first two tutorials in the list (below) assume you have completed the Launching Virtual Machines tutorial. I believe these are supposed to be ordered the opposite way. 

Launching and connecting
- Rebooting, Deleting, Rebuilding, Resizing
- Access using SSH and VNC
- Launching Virtual Machines

**Comment by andybotting** [comment]
Yeah you're right. We moved to listing these dynamically and it has resulted in poor ordering.

Thanks for reporting.
