### ISSUE TITLE
Cloudstor-setup command not working

### ISSUE THREAD

**Issue by srggrs** [NeCTAR-RC/tutorials#104]
I tried running `cloudstor-setup` but the script is not working. Error is with authentication (http 401 Unauthorized). I checked my credentials with `cloudstoR` R package and I can successfully login and list files and folders. So not sure what is going wrong.

I run the testing command manually without dumping the output:
```bash
curl -sL -w "%{http_code}\\n" -u "XXXX" -p "XXXXX" "https://cloudstor.aarnet.edu.au/plus/remote.php/webdav/"
```
and I get this output:
```bash
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>Too many failed login attempts. Try again in 5 minutes.</s:message>
</d:error>
401
```

Do you have any suggestions on how to get this fixed? Not sure event if this is the right place to report the problem.

**Comment by andybotting** [comment]
@srggrs Nectar support helpdesk is what you want. You can submit a ticket through our form at https://support.ehelp.edu.au/support/tickets/new or emailing support@ehelp.edu.au

cheers,
Andy
