### ISSUE TITLE
k8s tutorial yaml correction

### ISSUE THREAD

**Issue by sforsayeth** [NeCTAR-RC/tutorials#105]
Section 9, Volumes

Minor YAML edit needed in example template for 'nginxcinder.yaml'. The metadata label is in the wrong position
 
eg.
......
metadata:
  name: nginxcinder labels:
    app: nginxcinder
......

**Comment by ramson33** [comment]
thanks simon! will get onto this today!

**Comment by ramson33** [comment]
fix submitted for review!
