### ISSUE TITLE
How to move files from Virtual Desktop to local computer

### ISSUE THREAD

**Issue by Jeff-Intersect** [NeCTAR-RC/tutorials#107]
Hi Team,

I can drag and drop files from my local computer to the Virtual Desktop window. But I cannot move files from the Virtual Desktop to my local computer by drag and drop. Could you advise how I should do? Thanks!

Kind regards,
Jeff

**Comment by andybotting** [comment]
@Jeff-Intersect Try drag-and-dropping your file onto the `Download` folder within the GUACFS folder. That should initiate the download via the browser

**Comment by Jeff-Intersect** [comment]
Thanks @andybotting for your prompt response! It works. Awesome!

**Comment by andybotting** [comment]
We'll make sure the tutorial gets updated to include this, if it wasn't obvious! Thanks for your report

**Comment by Jeff-Intersect** [comment]
Hi @andybotting , I found a tiny issue. As shown below, there are two step 4 in the tutorial. Maybe change Overview to Step 0?
![image](https://user-images.githubusercontent.com/50306663/175225731-354bbb9c-69cd-407f-b4d6-edc508825d6e.png)

**Comment by ramson33** [comment]
Hi Jeff, can confirm the double up number issue has been fixed as well :)

**Comment by Jeff-Intersect** [comment]
Thanks Team! Much appreciated!
