### ISSUE TITLE
Inconsistent duration of instance shelving

### ISSUE THREAD

**Issue by civier** [NeCTAR-RC/tutorials#109]
In this https://tutorials.rc.nectar.org.au/virtual-desktop-service/04-managing-desktop tutorial page it says:

Keep an eye on the time ⏰
Once you have launched a Virtual Desktop, this desktop will be available for 14 days. After 14 days, the desktop will initiate an expiry process, with the instance shelved for **3 months**, and then deleted. You will receive email reminders at each stage of the expiry process. However, remember, you are able to extend your desktop for another 14 days, using the extend button as well.

However, this is the email I received from the system just yesterday:

Your ARDC Nectar Virtual Desktop will be shelved Nov. 19, 2022
Hi Oren Civier,
Your ARDC Nectar Virtual Desktop is now due to be shelved on Nov. 19, 2022, 11 p.m.. All currently running jobs will be terminated, your interactive session will be disconnected and the desktop will be turned off.
The shelved desktop will be kept for a further **30 days**. Finally, if the desktop has not been unshelved in the interim, the it will then be deleted.
If you wish to continue using it beyond that time, please visit the [ARDC Virtual Desktop Service](https://protect-au.mimecast.com/s/BIQkCgZo1ZsERWBztNJfhQ?domain=desktop.rc.nectar.org.au) site and use the Extend button to extend the lifetime for a further 14 days. If you no longer need the Desktop, please use the Delete button to delete it immediately.
This is the first warning.
Yours sincerely,
ARDC’s Nectar Research Cloud team

**So, which one is right? The tutorial or the notification email? Is the instance shelved from 3 months or 30 days?**

**Comment by crawley** [comment]
Hi Oren,

The email is correct.  The current policy (in production) is to expire shelved desktops after 30 days.

I will get someone to fix the out-of-date info in the Tutorial.

-- Steve
