### ISSUE TITLE
Cyberduck only downloads individual files not contents of folders (windows)

### ISSUE THREAD

**Issue by TimeScience** [NeCTAR-RC/tutorials#115]
Download of one or more files works fine but download of a folder just downloads an empty folder. Is there a way to force it to download the contents of a folder?
A colleague using cyberduck on linux doesn't have this problem so it is possibly a windows problem.
I'm using the most recent version of cyberduck and I'm on Win10

See Transfer log below. The files come down fine but the folders are downloaded as empty when they aren't.
Same issue happen if I try "synchronize" it creates the root folder with size of 0 B and then stops.

![image](https://github.com/NeCTAR-RC/tutorials/assets/3067588/0cd4dc13-2836-4c22-acf4-dfbf0504982d)

**Comment by andybotting** [comment]
Hey @TimeScience 

We don't actively test cyberduck, so I can't really comment, but I have had success using rclone in the past.

There's also a nice GUI tool here https://github.com/kapitainsky/RcloneBrowser

I've had a task on my todo list for ages to properly document how to set up Rclone for Nectar Object Storage, if you wanted to try it and needed help.

**Comment by TimeScience** [comment]
Hi Andy,

Thanks for the answer. I've installed rclone and tried to configure it to connect following the instructions here: https://support.ehelp.edu.au/support/solutions/articles/6000118791-vicnode-and-nectar-cloud-storage-use-cases-patterns-and-tools (which was the only rclone documentation I could find on the nectar site).

I'm getting a  "error listing: directory not found" error but those instruction don't seem to match the level of detail that rclone wants. I also tried using the credentials from the API access page. Bur for some of the fields in rclone I wasn't sure what to use since most of the named fields on the API access popup don't match what rclone is asking for. Is there better documentation somewhere or can you tell me which fields and url's and credentials go with which items in rclone?

Thanks

Tim

________________________________

**Comment by andybotting** [comment]
Hi @TimeScience 

It actually works quite well for me using the openrc file and the most basic rclone config you can get:

E.g.
```
OS_REGION_NAME=Melbourne
OS_PROJECT_DOMAIN_ID=default
OS_INTERFACE=public
OS_AUTH_URL=https://keystone.rc.nectar.org.au:5000/v3/
OS_USERNAME=<username>
OS_PROJECT_ID=<project id>
OS_USER_DOMAIN_NAME=Default
OS_PROJECT_NAME=<project name>
OS_PASSWORD=<pass>
OS_IDENTITY_API_VERSION=3
```

Then, my basic rclone config:

```~/.config/rclone/rclone.conf 
[nectar]
type = swift
env_auth = true
```

At this point, I can do:

```
rclone lsd nectar:
```

and it lists the containers I have.

**Comment by andybotting** [comment]
I've also managed to get a config without using the openrc file:

```
[nectar2]
type = swift
user = <username>
key = <password>
auth = https://keystone.rc.nectar.org.au:5000/v3
domain = Default
tenant = <project>
tenant_domain = Default
```

I know you can use Application Credentials too, which is probably a better choice than using your actual username/password too as you can easily revoke them.

Hope this helps!

**Comment by TimeScience** [comment]
This worked! and unlike cyberduck, rclone seems to actually download all files and subfolders rather than an empty file and then failing (which is what cyberduck on Windows does).

Thanks for your help.


________________________________

**Comment by andybotting** [comment]
No worries Tim, glad I could help!
