### ISSUE TITLE
nectar "convenience" method doco doesn't produce a public key

### ISSUE THREAD

**Issue by hooliowobbits** [NeCTAR-RC/tutorials#64]
at https://tutorials.rc.nectar.org.au/keypairs/03-convenience, following the doco will yield a private key, but no public key (the public key residing only within nectar).  in order to make a public key, it would have to be done manually:

1. inspecting the key at nectar
1. expending it out and finding the public component, copy that to clipboard.
1. write that to a new .pub file in ~/.ssh/
1. set the permissions correctly*

[*] The public key (.pub file) should be 644 (-rw-r--r--).

**Comment by JustBerkhout** [comment]
The key instruction here are only the bare essentials to enable access to Nectar. So the Nectar convenience method puts the public key right where it is needed: in the register in the Nectar account that generated it. No further action required.

users can regen their public key from the private key using ssh-keygen:
```bash
$ ssh-keygen -y -f ~/.ssh/id_rsa
```
I feel this is outside of the bare essentials cloud starter scope.
