### ISSUE TITLE
Insufficient content in sec-groups-101/04-apply

### ISSUE THREAD

**Issue by hooliowobbits** [NeCTAR-RC/tutorials#68]
this tutorial should show:
1. how to add a sec group to a new instance 
1. how to add a sec group to a running instance

https://tutorials.rc.nectar.org.au/sec-groups-101/04-apply

**Comment by JustBerkhout** [comment]
Added examples of adding sec groups at launch, and on running instance. Added notes/references that cloud starter users will have other tutorials ahead of them to explain in more detail.
