### ISSUE TITLE
Tutorial link broken link at cloud-starter/02-tutorials

### ISSUE THREAD

**Issue by hooliowobbits** [NeCTAR-RC/tutorials#76]
the link for `Command line, sudo and apt`at https://tutorials.rc.nectar.org.au/cloud-starter/02-tutorials points to https://tutorials.rc.nectar.org.au/cli-sudo-apt which returns a 404.  the correct link should be https://tutorials.rc.nectar.org.au/cli-101/01-overview

**Comment by JustBerkhout** [comment]
this was fixed in #84
