### ISSUE TITLE
unclear where to set the ubuntu passwd for vnc access

### ISSUE THREAD

**Issue by JustBerkhout** [NeCTAR-RC/tutorials#89]
In our workshop (Dec-2, UTas, Just and Julius) we found a number of participant making the mistake of attmpting to set the `ubuntu` user password, while not connected to their remote machine .

The instructions to set the ubuntu password using `sudo passwd ubuntu` should be clearer in indicating that the user needs to be connected to the instance, so that they are affecting the remote instance' ubuntu account/password.

**Comment by dmalby** [comment]
This is now clarified in the tutorial.
