### ISSUE TITLE
downloading keys from Nectar stumps users. 

### ISSUE THREAD

**Issue by JustBerkhout** [NeCTAR-RC/tutorials#90]
The _Nectar convenience method_ of downloading a private key from Nectar, results  in a few scenarios that confuse entry-level users. 

- Browser downloads private key to unsecure folder
- user needs to copy from unsecure folder to terminal accessible secure folder
- recommended windows-based terminals (MobaXterm and WSL) both have obscure and different locations for the /home directory, that tends to need bespoke explanation
- File permissions may or may not be set correctly for 
- custom key-names make key-specification with the `-i` flag required (as opposed to default key_name `id_rsa`

overall it seems that the `ssh-keygen` method is much more _convenient_ than the _Nectar convenience method_.  We should consider removing the Nectar Convenience method from the Nec tutorials, favouring the `ssh-keygen` method. 

An additional benefit of this would be that the tutorial indeed only teaches _one_ method, further simplifying the life of entry-level users.

**Comment by ramson33** [comment]
done - convenience method removed.
