### ISSUE TITLE
Enhancement for "About keys and Nectar"

### ISSUE THREAD

**Issue by mondkaefer** [NeCTAR-RC/tutorials#98]
Page: https://tutorials.rc.nectar.org.au/keypairs/02-about

In Auckland, and I think elsewhere as well, researchers can launch Windows instances.
While OpenSSH can be configured on Windows to allow key pair based login and end up with a command prompt, probably nobody uses it as user login mechanism.

So I'd probably tweak the first paragraph

> A Public-Private keypair is used in the Nectar instead of a password, to log on to any Virtual Machine (VM) you launch in Nectar.

to reflect that this applies to Linux VMs only, and add that some institutions offer Windows OS and the integration with institutional authentication mechanisms may vary and to check in with their institutional Nectar folks.

**Comment by ramson33** [comment]
note added to the keys tutorial
