### ISSUE TITLE
Connection error following 05-using-clis

### ISSUE THREAD

**Issue by julesghub** [NeCTAR-RC/tutorials#99]
Hi NeCTAR.
I have an error following https://tutorials.rc.nectar.org.au/openstack-cli/05-using-clis
I have downloaded the OpenStack client and setup my credentials. Upon trying some commands I'm unable to establish a connection.
Specifically:
```bash
julian@tank:~ $ openstack server list
Failed to discover available identity versions when contacting https://keystone.rc.nectar.org.au:5000/v3/. Attempting to parse version from URL.
Unable to establish connection to https://keystone.rc.nectar.org.au:5000/v3/auth/tokens: HTTPSConnectionPool(host='keystone.rc.nectar.org.au', port=5000): Max retries exceeded with url: /v3/auth/tokens (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7386a11820>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

```bash
[py38] julian@tank:~ $ openstack --version
openstack 5.2.1
```

Any ideas what the problem with establishing a connection is?
Thanks in advance.

**Comment by andybotting** [comment]
Hey @julesghub 

Can you send this through to support@ehelp.edu.au and our helpdesk team will be able to sort you out.

Thanks
